// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/moweilong/art-design-pro-go/internal/apiserver/biz"
	"github.com/moweilong/art-design-pro-go/internal/apiserver/pkg/validation"
	"github.com/moweilong/art-design-pro-go/internal/apiserver/store"
	"github.com/moweilong/art-design-pro-go/internal/pkg/auth"
	"github.com/moweilong/milady/pkg/authz"
	"github.com/moweilong/milady/pkg/options"
)

// Injectors from wire.go:

// NewServer sets up and create the web server with all necessary dependencies.
func NewServer(config *Config, jwtOptions *options.JWTOptions, redisOptions *options.RedisOptions) (*Server, error) {
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	authenticator, err := NewAuthenticator(jwtOptions, redisOptions)
	if err != nil {
		return nil, err
	}
	secretSetter := store.NewSecretSetter(datastore)
	authnImpl, err := auth.NewAuthn(secretSetter)
	if err != nil {
		return nil, err
	}
	authAuth := auth.NewAuth(authnImpl)
	bizBiz := biz.NewBiz(datastore, authenticator, authAuth)
	validator := validation.New(datastore)
	userRetriever := &UserRetriever{
		store: datastore,
	}
	v := authz.DefaultOptions()
	authzAuthz, err := authz.NewAuthz(db, v...)
	if err != nil {
		return nil, err
	}
	serverConfig := &ServerConfig{
		Config:    config,
		biz:       bizBiz,
		val:       validator,
		retriever: userRetriever,
		authz:     authzAuthz,
	}
	server, err := NewWebServer(serverConfig)
	if err != nil {
		return nil, err
	}
	apiserverServer := &Server{
		cfg: serverConfig,
		srv: server,
	}
	return apiserverServer, nil
}
