// This file defines the Protobuf messages for managing Users.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: apiserver/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_apiserver_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_apiserver_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Obj           string                 `protobuf:"bytes,3,opt,name=obj,proto3" json:"obj,omitempty"`
	Act           string                 `protobuf:"bytes,4,opt,name=act,proto3" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_apiserver_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *AuthorizeRequest) GetObj() string {
	if x != nil {
		return x.Obj
	}
	return ""
}

func (x *AuthorizeRequest) GetAct() string {
	if x != nil {
		return x.Act
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_apiserver_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Obj           string                 `protobuf:"bytes,2,opt,name=obj,proto3" json:"obj,omitempty"`
	Act           string                 `protobuf:"bytes,3,opt,name=act,proto3" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_apiserver_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetObj() string {
	if x != nil {
		return x.Obj
	}
	return ""
}

func (x *AuthRequest) GetAct() string {
	if x != nil {
		return x.Act
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_apiserver_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *AuthResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_apiserver_v1_auth_proto protoreflect.FileDescriptor

const file_apiserver_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x17apiserver/v1/auth.proto\x12\fapiserver.v1\"+\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\".\n" +
	"\x14AuthenticateResponse\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"H\n" +
	"\x10AuthorizeRequest\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03obj\x18\x03 \x01(\tR\x03obj\x12\x10\n" +
	"\x03act\x18\x04 \x01(\tR\x03act\"-\n" +
	"\x11AuthorizeResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"G\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03obj\x18\x02 \x01(\tR\x03obj\x12\x10\n" +
	"\x03act\x18\x03 \x01(\tR\x03act\"@\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowedB@Z>github.com/moweilong/art-design-pro-go/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_auth_proto_rawDescOnce sync.Once
	file_apiserver_v1_auth_proto_rawDescData []byte
)

func file_apiserver_v1_auth_proto_rawDescGZIP() []byte {
	file_apiserver_v1_auth_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_auth_proto_rawDesc), len(file_apiserver_v1_auth_proto_rawDesc)))
	})
	return file_apiserver_v1_auth_proto_rawDescData
}

var file_apiserver_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apiserver_v1_auth_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: apiserver.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 1: apiserver.v1.AuthenticateResponse
	(*AuthorizeRequest)(nil),     // 2: apiserver.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),    // 3: apiserver.v1.AuthorizeResponse
	(*AuthRequest)(nil),          // 4: apiserver.v1.AuthRequest
	(*AuthResponse)(nil),         // 5: apiserver.v1.AuthResponse
}
var file_apiserver_v1_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_auth_proto_init() }
func file_apiserver_v1_auth_proto_init() {
	if File_apiserver_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_auth_proto_rawDesc), len(file_apiserver_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_auth_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_auth_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_auth_proto_msgTypes,
	}.Build()
	File_apiserver_v1_auth_proto = out.File
	file_apiserver_v1_auth_proto_goTypes = nil
	file_apiserver_v1_auth_proto_depIdxs = nil
}
