// This file defines the Protobuf messages for managing Secrets.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: apiserver/v1/secret.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Secret represents a secret with its metadata.
type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SecretID      string                 `protobuf:"bytes,3,opt,name=secretID,proto3" json:"secretID,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Expires       int64                  `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetSecretID() string {
	if x != nil {
		return x.SecretID
	}
	return ""
}

func (x *Secret) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Secret) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Secret) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Secret) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateSecretRequest represents the request message for creating a new secret.
type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expires       int64                  `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *CreateSecretRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreateSecretResponse represents the response message for a successful secret creation.
type CreateSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SecretID is the unique identifier of the newly created secret.
	SecretID      string `protobuf:"bytes,1,opt,name=secretID,proto3" json:"secretID,omitempty"` // TODO: Add additional fields to return if needed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecretResponse) GetSecretID() string {
	if x != nil {
		return x.SecretID
	}
	return ""
}

// UpdateSecretRequest represents the request message for updating an existing secret.
type UpdateSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"name"
	Name          string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" uri:"name"`
	Expires       *int64  `protobuf:"varint,2,opt,name=expires,proto3,oneof" json:"expires,omitempty"`
	Status        *int32  `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Description   *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretRequest) GetExpires() int64 {
	if x != nil && x.Expires != nil {
		return *x.Expires
	}
	return 0
}

func (x *UpdateSecretRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateSecretRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// UpdateSecretResponse represents the response message for a successful secret update.
type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{4}
}

// DeleteSecretRequest represents the request message for deleting one or more secrets.
type DeleteSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"name"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" uri:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteSecretResponse represents the response message for a successful secret deletion.
type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{6}
}

// GetSecretRequest represents the request message for retrieving a specific secret.
type GetSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SecretID is the unique identifier of the secret to retrieve.
	// @gotags: uri:"name"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" uri:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetSecretResponse represents the response message for a successful retrieval of a secret.
type GetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret is the retrieved secret object.
	Secret        *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{8}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// ListSecretRequest represents the request message for listing secrets
// with pagination and optional filters.
type ListSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the starting point of the list for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// Limit is the maximum number of secrets to return.
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"` // TODO: Add additional query fields if needed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretRequest) Reset() {
	*x = ListSecretRequest{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretRequest) ProtoMessage() {}

func (x *ListSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretRequest.ProtoReflect.Descriptor instead.
func (*ListSecretRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecretRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSecretRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListSecretResponse represents the response message for listing secrets.
type ListSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TotalCount is the total number of secrets matching the query.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Secret is the list of secrets in the current page.
	Secrets       []*Secret `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretResponse) Reset() {
	*x = ListSecretResponse{}
	mi := &file_apiserver_v1_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretResponse) ProtoMessage() {}

func (x *ListSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretResponse.ProtoReflect.Descriptor instead.
func (*ListSecretResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_secret_proto_rawDescGZIP(), []int{10}
}

func (x *ListSecretResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSecretResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_apiserver_v1_secret_proto protoreflect.FileDescriptor

const file_apiserver_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x19apiserver/v1/secret.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x02\n" +
	"\x06Secret\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsecretID\x18\x03 \x01(\tR\bsecretID\x12\x1c\n" +
	"\tsecretKey\x18\x04 \x01(\tR\tsecretKey\x12\x18\n" +
	"\aexpires\x18\x05 \x01(\x03R\aexpires\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"e\n" +
	"\x13CreateSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\x03R\aexpires\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"2\n" +
	"\x14CreateSecretResponse\x12\x1a\n" +
	"\bsecretID\x18\x01 \x01(\tR\bsecretID\"\xb3\x01\n" +
	"\x13UpdateSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\aexpires\x18\x02 \x01(\x03H\x00R\aexpires\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x01R\x06status\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01B\n" +
	"\n" +
	"\b_expiresB\t\n" +
	"\a_statusB\x0e\n" +
	"\f_description\"\x16\n" +
	"\x14UpdateSecretResponse\")\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteSecretResponse\"&\n" +
	"\x10GetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x11GetSecretResponse\x12,\n" +
	"\x06secret\x18\x01 \x01(\v2\x14.apiserver.v1.SecretR\x06secret\"A\n" +
	"\x11ListSecretRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"Z\n" +
	"\x12ListSecretResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12.\n" +
	"\asecrets\x18\x02 \x03(\v2\x14.apiserver.v1.SecretR\asecretsB@Z>github.com/moweilong/art-design-pro-go/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_secret_proto_rawDescOnce sync.Once
	file_apiserver_v1_secret_proto_rawDescData []byte
)

func file_apiserver_v1_secret_proto_rawDescGZIP() []byte {
	file_apiserver_v1_secret_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_secret_proto_rawDesc), len(file_apiserver_v1_secret_proto_rawDesc)))
	})
	return file_apiserver_v1_secret_proto_rawDescData
}

var file_apiserver_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_secret_proto_goTypes = []any{
	(*Secret)(nil),                // 0: apiserver.v1.Secret
	(*CreateSecretRequest)(nil),   // 1: apiserver.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil),  // 2: apiserver.v1.CreateSecretResponse
	(*UpdateSecretRequest)(nil),   // 3: apiserver.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),  // 4: apiserver.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),   // 5: apiserver.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 6: apiserver.v1.DeleteSecretResponse
	(*GetSecretRequest)(nil),      // 7: apiserver.v1.GetSecretRequest
	(*GetSecretResponse)(nil),     // 8: apiserver.v1.GetSecretResponse
	(*ListSecretRequest)(nil),     // 9: apiserver.v1.ListSecretRequest
	(*ListSecretResponse)(nil),    // 10: apiserver.v1.ListSecretResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_secret_proto_depIdxs = []int32{
	11, // 0: apiserver.v1.Secret.createdAt:type_name -> google.protobuf.Timestamp
	11, // 1: apiserver.v1.Secret.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: apiserver.v1.GetSecretResponse.secret:type_name -> apiserver.v1.Secret
	0,  // 3: apiserver.v1.ListSecretResponse.secrets:type_name -> apiserver.v1.Secret
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_apiserver_v1_secret_proto_init() }
func file_apiserver_v1_secret_proto_init() {
	if File_apiserver_v1_secret_proto != nil {
		return
	}
	file_apiserver_v1_secret_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_secret_proto_rawDesc), len(file_apiserver_v1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_secret_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_secret_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_secret_proto_msgTypes,
	}.Build()
	File_apiserver_v1_secret_proto = out.File
	file_apiserver_v1_secret_proto_goTypes = nil
	file_apiserver_v1_secret_proto_depIdxs = nil
}
