// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: apiserver/v1/usercenter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apiserver_v1_usercenter_proto protoreflect.FileDescriptor

const file_apiserver_v1_usercenter_proto_rawDesc = "" +
	"\n" +
	"\x1dapiserver/v1/usercenter.proto\x12\fapiserver.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19apiserver/v1/secret.proto\x1a\x17apiserver/v1/user.proto\x1a\x17apiserver/v1/auth.proto2\xb1\x0e\n" +
	"\n" +
	"UserCenter\x12X\n" +
	"\x05Login\x12\x1a.apiserver.v1.LoginRequest\x1a\x18.apiserver.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12_\n" +
	"\x06Logout\x12\x1b.apiserver.v1.LogoutRequest\x1a\x1c.apiserver.v1.LogoutResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12n\n" +
	"\fRefreshToken\x12!.apiserver.v1.RefreshTokenRequest\x1a\x18.apiserver.v1.LoginReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/auth/refresh-token\x12w\n" +
	"\fAuthenticate\x12!.apiserver.v1.AuthenticateRequest\x1a\".apiserver.v1.AuthenticateResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/auth/authenticate\x12k\n" +
	"\tAuthorize\x12\x1e.apiserver.v1.AuthorizeRequest\x1a\x1f.apiserver.v1.AuthorizeResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/auth/authorize\x12W\n" +
	"\x04Auth\x12\x19.apiserver.v1.AuthRequest\x1a\x1a.apiserver.v1.AuthResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/auth/auth\x12e\n" +
	"\n" +
	"CreateUser\x12\x1f.apiserver.v1.CreateUserRequest\x1a .apiserver.v1.CreateUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12n\n" +
	"\n" +
	"UpdateUser\x12\x1f.apiserver.v1.UpdateUserRequest\x1a .apiserver.v1.UpdateUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/users/{userID}\x12k\n" +
	"\n" +
	"DeleteUser\x12\x1f.apiserver.v1.DeleteUserRequest\x1a .apiserver.v1.DeleteUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/users/{userID}\x12b\n" +
	"\aGetUser\x12\x1c.apiserver.v1.GetUserRequest\x1a\x1d.apiserver.v1.GetUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/users/{userID}\x12\\\n" +
	"\bListUser\x12\x1d.apiserver.v1.ListUserRequest\x1a\x1e.apiserver.v1.ListUserResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x8a\x01\n" +
	"\x0eUpdatePassword\x12#.apiserver.v1.UpdatePasswordRequest\x1a$.apiserver.v1.UpdatePasswordResponse\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/v1/users/{userID}/update-password\x12m\n" +
	"\fCreateSecret\x12!.apiserver.v1.CreateSecretRequest\x1a\".apiserver.v1.CreateSecretResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/secrets\x12t\n" +
	"\fUpdateSecret\x12!.apiserver.v1.UpdateSecretRequest\x1a\".apiserver.v1.UpdateSecretResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/secrets/{name}\x12q\n" +
	"\fDeleteSecret\x12!.apiserver.v1.DeleteSecretRequest\x1a\".apiserver.v1.DeleteSecretResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/secrets/{name}\x12h\n" +
	"\tGetSecret\x12\x1e.apiserver.v1.GetSecretRequest\x1a\x1f.apiserver.v1.GetSecretResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/secrets/{name}\x12d\n" +
	"\n" +
	"ListSecret\x12\x1f.apiserver.v1.ListSecretRequest\x1a .apiserver.v1.ListSecretResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/secretsB@Z>github.com/moweilong/art-design-pro-go/pkg/api/apiserver/v1;v1b\x06proto3"

var file_apiserver_v1_usercenter_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: apiserver.v1.LoginRequest
	(*LogoutRequest)(nil),          // 1: apiserver.v1.LogoutRequest
	(*RefreshTokenRequest)(nil),    // 2: apiserver.v1.RefreshTokenRequest
	(*AuthenticateRequest)(nil),    // 3: apiserver.v1.AuthenticateRequest
	(*AuthorizeRequest)(nil),       // 4: apiserver.v1.AuthorizeRequest
	(*AuthRequest)(nil),            // 5: apiserver.v1.AuthRequest
	(*CreateUserRequest)(nil),      // 6: apiserver.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),      // 7: apiserver.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),      // 8: apiserver.v1.DeleteUserRequest
	(*GetUserRequest)(nil),         // 9: apiserver.v1.GetUserRequest
	(*ListUserRequest)(nil),        // 10: apiserver.v1.ListUserRequest
	(*UpdatePasswordRequest)(nil),  // 11: apiserver.v1.UpdatePasswordRequest
	(*CreateSecretRequest)(nil),    // 12: apiserver.v1.CreateSecretRequest
	(*UpdateSecretRequest)(nil),    // 13: apiserver.v1.UpdateSecretRequest
	(*DeleteSecretRequest)(nil),    // 14: apiserver.v1.DeleteSecretRequest
	(*GetSecretRequest)(nil),       // 15: apiserver.v1.GetSecretRequest
	(*ListSecretRequest)(nil),      // 16: apiserver.v1.ListSecretRequest
	(*LoginReply)(nil),             // 17: apiserver.v1.LoginReply
	(*LogoutResponse)(nil),         // 18: apiserver.v1.LogoutResponse
	(*AuthenticateResponse)(nil),   // 19: apiserver.v1.AuthenticateResponse
	(*AuthorizeResponse)(nil),      // 20: apiserver.v1.AuthorizeResponse
	(*AuthResponse)(nil),           // 21: apiserver.v1.AuthResponse
	(*CreateUserResponse)(nil),     // 22: apiserver.v1.CreateUserResponse
	(*UpdateUserResponse)(nil),     // 23: apiserver.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),     // 24: apiserver.v1.DeleteUserResponse
	(*GetUserResponse)(nil),        // 25: apiserver.v1.GetUserResponse
	(*ListUserResponse)(nil),       // 26: apiserver.v1.ListUserResponse
	(*UpdatePasswordResponse)(nil), // 27: apiserver.v1.UpdatePasswordResponse
	(*CreateSecretResponse)(nil),   // 28: apiserver.v1.CreateSecretResponse
	(*UpdateSecretResponse)(nil),   // 29: apiserver.v1.UpdateSecretResponse
	(*DeleteSecretResponse)(nil),   // 30: apiserver.v1.DeleteSecretResponse
	(*GetSecretResponse)(nil),      // 31: apiserver.v1.GetSecretResponse
	(*ListSecretResponse)(nil),     // 32: apiserver.v1.ListSecretResponse
}
var file_apiserver_v1_usercenter_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.UserCenter.Login:input_type -> apiserver.v1.LoginRequest
	1,  // 1: apiserver.v1.UserCenter.Logout:input_type -> apiserver.v1.LogoutRequest
	2,  // 2: apiserver.v1.UserCenter.RefreshToken:input_type -> apiserver.v1.RefreshTokenRequest
	3,  // 3: apiserver.v1.UserCenter.Authenticate:input_type -> apiserver.v1.AuthenticateRequest
	4,  // 4: apiserver.v1.UserCenter.Authorize:input_type -> apiserver.v1.AuthorizeRequest
	5,  // 5: apiserver.v1.UserCenter.Auth:input_type -> apiserver.v1.AuthRequest
	6,  // 6: apiserver.v1.UserCenter.CreateUser:input_type -> apiserver.v1.CreateUserRequest
	7,  // 7: apiserver.v1.UserCenter.UpdateUser:input_type -> apiserver.v1.UpdateUserRequest
	8,  // 8: apiserver.v1.UserCenter.DeleteUser:input_type -> apiserver.v1.DeleteUserRequest
	9,  // 9: apiserver.v1.UserCenter.GetUser:input_type -> apiserver.v1.GetUserRequest
	10, // 10: apiserver.v1.UserCenter.ListUser:input_type -> apiserver.v1.ListUserRequest
	11, // 11: apiserver.v1.UserCenter.UpdatePassword:input_type -> apiserver.v1.UpdatePasswordRequest
	12, // 12: apiserver.v1.UserCenter.CreateSecret:input_type -> apiserver.v1.CreateSecretRequest
	13, // 13: apiserver.v1.UserCenter.UpdateSecret:input_type -> apiserver.v1.UpdateSecretRequest
	14, // 14: apiserver.v1.UserCenter.DeleteSecret:input_type -> apiserver.v1.DeleteSecretRequest
	15, // 15: apiserver.v1.UserCenter.GetSecret:input_type -> apiserver.v1.GetSecretRequest
	16, // 16: apiserver.v1.UserCenter.ListSecret:input_type -> apiserver.v1.ListSecretRequest
	17, // 17: apiserver.v1.UserCenter.Login:output_type -> apiserver.v1.LoginReply
	18, // 18: apiserver.v1.UserCenter.Logout:output_type -> apiserver.v1.LogoutResponse
	17, // 19: apiserver.v1.UserCenter.RefreshToken:output_type -> apiserver.v1.LoginReply
	19, // 20: apiserver.v1.UserCenter.Authenticate:output_type -> apiserver.v1.AuthenticateResponse
	20, // 21: apiserver.v1.UserCenter.Authorize:output_type -> apiserver.v1.AuthorizeResponse
	21, // 22: apiserver.v1.UserCenter.Auth:output_type -> apiserver.v1.AuthResponse
	22, // 23: apiserver.v1.UserCenter.CreateUser:output_type -> apiserver.v1.CreateUserResponse
	23, // 24: apiserver.v1.UserCenter.UpdateUser:output_type -> apiserver.v1.UpdateUserResponse
	24, // 25: apiserver.v1.UserCenter.DeleteUser:output_type -> apiserver.v1.DeleteUserResponse
	25, // 26: apiserver.v1.UserCenter.GetUser:output_type -> apiserver.v1.GetUserResponse
	26, // 27: apiserver.v1.UserCenter.ListUser:output_type -> apiserver.v1.ListUserResponse
	27, // 28: apiserver.v1.UserCenter.UpdatePassword:output_type -> apiserver.v1.UpdatePasswordResponse
	28, // 29: apiserver.v1.UserCenter.CreateSecret:output_type -> apiserver.v1.CreateSecretResponse
	29, // 30: apiserver.v1.UserCenter.UpdateSecret:output_type -> apiserver.v1.UpdateSecretResponse
	30, // 31: apiserver.v1.UserCenter.DeleteSecret:output_type -> apiserver.v1.DeleteSecretResponse
	31, // 32: apiserver.v1.UserCenter.GetSecret:output_type -> apiserver.v1.GetSecretResponse
	32, // 33: apiserver.v1.UserCenter.ListSecret:output_type -> apiserver.v1.ListSecretResponse
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_usercenter_proto_init() }
func file_apiserver_v1_usercenter_proto_init() {
	if File_apiserver_v1_usercenter_proto != nil {
		return
	}
	file_apiserver_v1_secret_proto_init()
	file_apiserver_v1_user_proto_init()
	file_apiserver_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_usercenter_proto_rawDesc), len(file_apiserver_v1_usercenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiserver_v1_usercenter_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_usercenter_proto_depIdxs,
	}.Build()
	File_apiserver_v1_usercenter_proto = out.File
	file_apiserver_v1_usercenter_proto_goTypes = nil
	file_apiserver_v1_usercenter_proto_depIdxs = nil
}
